/** Human labels for Zod / API field paths shown in validation errors. */
export const FIELD_LABELS: Record<string, string> = {
  email: 'Email',
  password: 'Password',
  firstName: 'First name',
  lastName: 'Last name',
  refreshToken: 'Refresh token',
  token: 'Token',
  code: 'Code',
  name: 'Name',
  slug: 'Slug',
  description: 'Description',
  sortOrder: 'Sort order',
  translations: 'Translations',
  locale: 'Locale',
  title: 'Title',
  excerpt: 'Excerpt',
  body: 'Body',
  categoryId: 'Category',
  brandId: 'Brand',
  variants: 'Variants',
  sku: 'SKU',
  price: 'Price',
  prices: 'Prices',
  compareAtPrice: 'Compare-at price',
  compareAtAmount: 'Compare-at amount',
  amount: 'Amount',
  currency: 'Currency',
  stock: 'Stock',
  weightGrams: 'Weight (grams)',
  barcode: 'Barcode',
  isActive: 'Active',
  status: 'Status',
  shortDescription: 'Short description',
  benefits: 'Benefits',
  howToUse: 'How to use',
  suitableFor: 'Suitable for',
  imageMediaIds: 'Images',
  imageUrl: 'Image URL',
  isIncoming: 'Incoming',
  incomingAt: 'Incoming date',
  quantityDelta: 'Quantity change',
  reason: 'Reason',
  note: 'Note',
  variantId: 'Variant',
  quantity: 'Quantity',
  fullName: 'Full name',
  line1: 'Address line 1',
  line2: 'Address line 2',
  city: 'City',
  region: 'Region',
  postalCode: 'Postal code',
  country: 'Country',
  phone: 'Phone',
  cartId: 'Cart',
  shippingAddress: 'Shipping address',
  shippingMethodId: 'Shipping method',
  paymentMethod: 'Payment method',
  startsAt: 'Start date',
  endsAt: 'End date',
  publishedAt: 'Published date',
  coverMediaId: 'Cover media',
  galleryMediaIds: 'Gallery images',
  recommendedProductIds: 'Recommended products',
  tags: 'Tags',
  productScope: 'Product scope',
  productTags: 'Product tags',
  ruleIsNew: 'New products only',
  ruleMinPriceUsd: 'Minimum price (USD)',
  ruleMinRating: 'Minimum rating',
  placement: 'Placement',
  href: 'Link URL',
  imageMediaId: 'Banner image',
  ctaLabel: 'Button label',
  subtitle: 'Subtitle',
  tag: 'Tag',
  taxRateBps: 'Tax rate',
  freeShippingThreshold: 'Free shipping threshold',
  freeShippingEnabled: 'Free shipping enabled',
  domesticShipping: 'Domestic shipping',
  internationalShipping: 'International shipping',
  domesticCountries: 'Domestic countries',
  cashOnDeliveryEnabled: 'Cash on delivery',
  cardPaymentEnabled: 'Card payment',
  stripeEnabled: 'Stripe',
  stripeSecretKey: 'Stripe secret key',
  stripePublishableKey: 'Stripe publishable key',
  konnectEnabled: 'Konnect',
  konnectApiKey: 'Konnect API key',
  konnectWalletId: 'Konnect wallet ID',
  konnectSandbox: 'Konnect sandbox',
  shippingMethods: 'Shipping methods',
  rating: 'Rating',
  q: 'Search',
  minPrice: 'Minimum price',
  maxPrice: 'Maximum price',
  page: 'Page',
  pageSize: 'Page size',
  limit: 'Limit',
  productIds: 'Product IDs',
  percentOff: 'Percent off',
  amountOff: 'Amount off',
  minSubtotal: 'Minimum subtotal',
  type: 'Type',
};

export function fieldPathToLabel(path: string): string {
  if (FIELD_LABELS[path]) return FIELD_LABELS[path];
  const segments = path.split('.');
  const last = segments[segments.length - 1] ?? path;
  if (FIELD_LABELS[last]) return FIELD_LABELS[last];
  return last
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
}
